<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>技术 on 乾之 三爻</title>
    <link>https://yokonsan.com/tags/%E6%8A%80%E6%9C%AF/</link>
    <description>Recent content in 技术 on 乾之 三爻</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en</language>
    <lastBuildDate>Sun, 29 Jul 2018 14:05:37 +0800</lastBuildDate><atom:link href="https://yokonsan.com/tags/%E6%8A%80%E6%9C%AF/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Flask的经典错误</title>
      <link>https://yokonsan.com/posts/2018/7/flask-classic-error/</link>
      <pubDate>Sun, 29 Jul 2018 14:05:37 +0800</pubDate>
      
      <guid>https://yokonsan.com/posts/2018/7/flask-classic-error/</guid>
      <description>在编写 Flask 应用的单元测试，离线应用时候经常会遇到，*RuntimeError: Working outside of application context.*的报错。这个报错是在没有激活程序上下文情况下，进行了一些程序上下文或请求上下文的操作。先看下面的两</description>
    </item>
    
  </channel>
</rss>
